name: LiveTranscribe
options:
  minimumXcodeGenVersion: 2.30.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
packages: {}
targets:
  LiveTranscribe:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: ios/LiveTranscribe/Sources
    info:
      path: ios/LiveTranscribe/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.LiveTranscribe
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "YOUR_TEAM_ID"
        PRODUCT_NAME: "Live Transcribe"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: "Live Transcribe"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
      Release:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        PROVISIONING_PROFILE_SPECIFIER: ""
  LiveTranscribeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: ios/LiveTranscribe/Tests
    settings:
      base:
        TEST_HOST: ""
    dependencies:
      - target: LiveTranscribe
schemes:
  LiveTranscribe:
    build:
      targets:
        LiveTranscribe: all
        LiveTranscribeTests: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LiveTranscribeTests
    run:
      config: Debug
