name: Deploy to App Store
on:
  workflow_dispatch:
    inputs:
      upload_to_testflight:
        description: 'Upload to TestFlight'
        required: true
        default: true
        type: boolean

jobs:
  build_and_deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Install Provisioning Profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.yourcompany.LiveTranscribe
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Update Info.plist with token endpoint
        run: |
          /usr/libexec/PlistBuddy -c "Set :SPEECH_TOKEN_ENDPOINT ${{ secrets.SPEECH_TOKEN_ENDPOINT }}" ios/LiveTranscribe/Info.plist

      - name: Build and Archive
        run: |
          xcodebuild archive \
            -project LiveTranscribe.xcodeproj \
            -scheme LiveTranscribe \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath ./LiveTranscribe.xcarchive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="Live Transcribe Distribution" \
            CODE_SIGN_IDENTITY="iPhone Distribution"

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ./LiveTranscribe.xcarchive \
            -exportPath ./export \
            -exportOptionsPlist ./scripts/ExportOptions.plist

      - name: Upload to TestFlight
        if: ${{ github.event.inputs.upload_to_testflight == 'true' }}
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ./export/LiveTranscribe.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LiveTranscribe-IPA
          path: ./export/LiveTranscribe.ipa
