name: Deploy Azure Function - Speech Token

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          slot-name: Production
          package: azure/functions
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Configure app settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          app-settings-json: |
            [
              {"name":"SPEECH_KEY","value":"${{ secrets.SPEECH_KEY }}","slotSetting":false},
              {"name":"SPEECH_REGION","value":"${{ secrets.SPEECH_REGION }}","slotSetting":false}
            ]
