name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject secrets into Info.plist
        run: |
          /usr/libexec/PlistBuddy -c "Set :SPEECH_TOKEN_ENDPOINT $SPEECH_TOKEN_ENDPOINT" ios/LiveTranscribe/Info.plist
        env:
          SPEECH_TOKEN_ENDPOINT: ${{ secrets.SPEECH_TOKEN_ENDPOINT }}

      - name: Token endpoint health check
        if: ${{ secrets.SPEECH_TOKEN_ENDPOINT != '' }}
        run: |
          STATUS=$(curl -s -o /tmp/out.json -w "%{http_code}" "$SPEECH_TOKEN_ENDPOINT")
          echo "Status: $STATUS"
          cat /tmp/out.json || true
          if [ "$STATUS" -lt 200 ] || [ "$STATUS" -gt 299 ]; then exit 1; fi
        env:
          SPEECH_TOKEN_ENDPOINT: ${{ secrets.SPEECH_TOKEN_ENDPOINT }}


      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Install xcpretty
        run: |
          sudo gem install xcpretty

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build
        run: |
          xcodebuild -project LiveTranscribe.xcodeproj \
            -scheme LiveTranscribe \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build | xcpretty

      - name: Test
        run: |
          xcodebuild -project LiveTranscribe.xcodeproj \
            -scheme LiveTranscribe \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            test | xcpretty
